"""created field added Kitiki

Revision ID: 76e1892a593f
Revises: 6abcc766f3e6
Create Date: 2022-01-24 18:31:52.734683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76e1892a593f'
down_revision = '6abcc766f3e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kitiki', sa.Column('created', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kitiki', 'created')
    # ### end Alembic commands ###
