version: "3.1"

services:
  application:
    build: .
    environment:
      - USERNAME=nina
      - PASSWORD=qwerty
      - HOST=postgres-kitiki
      - PORT=5432
      - DBNAME=kitiki
    ports:
      - "5004:5003"
    networks:
      - kitiki-network
    depends_on:
      - postgres


  postgres:
    image: postgres:10
    restart: always
    container_name: postgres-kitiki
    environment:
      - POSTGRES_USER=nina
      - POSTGRES_PASSWORD=qwerty
      - POSTGRES_DB=kitiki
    ports:
      - "5002:5432"
    networks:
      - kitiki-network
    volumes:
      - ./postgres-data:/var/lib/postgresql/data


networks:
  kitiki-network:
    driver: bridge
